version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: frkn123
      POSTGRES_USER: furkan
      POSTGRES_DB: eva_exchange
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: furkan@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"